### ISSUE TITLE
Get balances for some wallets failed for the `lastModifiedTime` is null

### ISSUE THREAD

**Issue by AhmedHanafy725** [Soneso/stellar_flutter_sdk#105]
### Steps

```dart
import 'package:stellar_flutter_sdk/stellar_flutter_sdk.dart';

final StellarSDK sdk = StellarSDK.PUBLIC;
await sdk.accounts.account("GAENMQNQZDNFWDYMOGUAHHZVLCA4NU4XAYWYNJFWPZMHVYL4E2ZEWL2I");
```

### Result

```bash
type 'Null' is not a subtype of type 'String'
#0      new AccountResponse.fromJson (package:stellar_flutter_sdk/src/responses/account_response.dart:86:11)
#1      ResponseConverter.fromJson (package:stellar_flutter_sdk/src/responses/response.dart:163:32)
#2      ResponseHandler.handleResponse (package:stellar_flutter_sdk/src/requests/request_builder.dart:188:34)
```

**Comment by christian-rogobete** [comment]
Hello @AhmedHanafy725. thank you for adding this issue. It has been fixed in [release 1.8.9](https://github.com/Soneso/stellar_flutter_sdk/releases/tag/1.8.9)
